### ISSUE TITLE
Visualisation in Paraview

### ISSUE THREAD

**Issue by tzahtila** [dpzwick/ppiclF#36]
Hi, 

I am trying to visualise the output of the Stokes2D, so I open the par00001.vtu file. However, once in paraview, the fields I am able to select: y01,y02,y03,y04, rpro01, tag01,tag02,tag03. 

I am scratching my head how I should visualise the particles? 

Kind regards.

**Comment by dpzwick** [comment]
Hello @tzahtila . Thank you for looking at this. I will get around to updating the documentation more explicitly, but these are defined in the [H-File](https://dpzwick.github.io/ppiclF-doc/user/hfile.html). The variables y01, y02, y03, y04 correspond to PPICLF_LRS number of solution variables. So in the Stokes 2D case, this corresponds to PPICLF_JX (x coordinate), PPICLF_JY (y coordinate), PPICLF_JVX (x velocity), and PPICLF_JVY (y velocity) as detailed [here](https://dpzwick.github.io/ppiclF-doc/examples/stokes_2d.html#user-interface).

The variable rpro01 corresponds to the PPICLF_LRP number of properties for each particle (also defined in the H-File). In this case, this is the particle time scale (PPICLF_R_JTAUP).

The tag## variables aren't necessary, but for some cases you may want to uniquely identify a particle throughout a simulation, so that is what these are for. The unique combination of (tag01, tag02, tag03) will never change for each particle, even if the simulation is restarted, other particles are added, etc.
