### ISSUE TITLE
Nek has has been compiled for number of elements/proc

### ISSUE THREAD

**Issue by tzahtila** [dpzwick/ppiclF#39]
Hi, 

1. I have taken the "Nek5000/examples/turbChannel" case and copied it to a new case "01_turbChannel_p2d".

2. I copy the makenek file from ppiclf/examples/Nek5000/makenek, in order to link the library to ppiclf.

The compilation succeeds, but when I try to run with 8 processors, I get the following error message:

                                      

```
  Reading /home/bz/nek_cases/01_turbChannel_p2d/turbChannel.re2    

  Error: Nek has has been compiled for
         number of elements/proc  (lelt):        1304
         total number of elements (lelg):        1300
  This run requires:
     lelt >=          192  for np =            8
     lelg >=         1536


an error occured: dying ...
```

I get a similar error irrespective of the number of MPI ranks.

**Comment by tzahtila** [comment]
Hi David,

I have managed to find the problem.

I believe that the SIZE file in ppiclf/source should match that in your case directory.

I think it may be useful to include this in the steps under ppiclF-doc/examples/Nek5000 compiling and running. Or perhaps I have overlooked something more simple? 

Kind regards.

**Comment by dpzwick** [comment]
Thank you for posting! Yes, this is true. The overlap mesh in Nek5000 should have LX1 = PPICLF_LEX, LY1 = PPICLF_LEY, and LZ1 = PPICLF_LEZ. The variable PPICLF_LEE is not directly equivalent to to LELT since the overlap mesh that ppiclF sees depends on the processors and particle distribution throughout the mesh (although for a  lot of cases LELT is a good starting point.)

That being said, what is in the ppiclf/examples/Nek5000/SIZE and ppiclf/examples/Nek5000/user_routines/PPICLF_USER.h do match at least in LX1, LY1, LZ1 (which is required). PPICLF_LEE and LELT do not match and they don't need to. It will really depend on the processor count. Sometimes it takes some tuning of PPICLF_LEE to get the right number. You can estimate it though by having a good idea of how your particles will be distributed on average in the spectral element mesh and how the binning algorithm stores particle data (see here: https://dpzwick.github.io/ppiclF-doc/algorithms/particle_storage.html). There is actually a matlab/octave script at the bottom of the page which you can use to help get an estimate for exactly how the binning algorithm works if needed.

In your case though, I think this is a Nek5000 issue since lpmax=4 in the SIZE file. If you want to run Nek5000 with 8 ranks, you have to change this. Hopefully this helps.

**Comment by hashthug-create** [comment]
Hello I have similar error , I am running on two ranks and it shows me the following error .

 !![image](https://user-images.githubusercontent.com/126136171/224432602-ab340f70-c6f1-402a-8c56-acec51db12e3.jpeg)
